In [5]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"D:\PycharmProjects\pythonProject\U23AI113\ML_lAB\LAB_5\archive (5)\Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [41]:
y=np.array([1 if name=='Iris-setosa' else 0 for name in df['Species']]).reshape(-1,1)
y
#y = np.array([1 if i==name else 0 for i in df['Species']]).reshape(-1,1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
y=np.array([1 if name=='Iris-setosa' else 0 for name in df['Species']]).reshape(-1,1)
y.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
y.flatten()==1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [81]:
#y[y.flatten()==1]

In [46]:
10/3

3.3333333333333335

In [47]:
10//3

3

In [49]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack(([a]*3, b))
result


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [12]:
def mak_dataset(name):
    lis=[]
    for i in df['Species']:
        if i== name:
            lis.append(1)
        else: lis.append(0)
    return np.array(lis).reshape(df.shape[0],-1)

Iris_setosa = mak_dataset('Iris-setosa')
Iris_setosa.shape

(150, 1)

In [13]:
Iris_versicolor=mak_dataset('Iris-versicolor')
Iris_virginica=mak_dataset('Iris-virginica')

In [14]:
X = df.drop(columns=['Id','Species']).values
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [15]:
mean=X.mean(axis=0)
mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

In [16]:
std=X.std(axis=0)
std

array([0.82530129, 0.43214658, 1.75852918, 0.76061262])

In [17]:
X=(X-mean)/std
X[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [18]:
c=np.ones((X.shape[0],1))
c.shape
X=np.hstack([c,X])
X.shape

(150, 5)

In [80]:
#Iris_setosa

In [20]:
cls_idx=np.where(Iris_setosa==1)
cls_idx

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]))

In [26]:
def train_val_split(X,y,train_size,val_size,seed=113):
    np.random.seed(seed)
    classes = np.unique(y)
    train_idx, val_idx = [], []
    for c in classes:
        cls_idx=np.where(y==c)[0]
        np.random.shuffle(cls_idx)
        n_total=len(cls_idx)
        n_train=int(n_total*train_size)
        train_idx.extend(cls_idx[:n_train])
        val_idx.extend(cls_idx[n_train:])
    np.random.shuffle(train_idx)
    np.random.shuffle(val_idx)
    return X[train_idx],y[train_idx],X[val_idx],y[val_idx]

In [27]:
#'Iris-setosa', 'Iris-versicolor', 'Iris-virginica'
X_train,Iris_setosa_train,X_val,Iris_setosa_val = train_val_split(X,Iris_setosa,0.8,0.2)
print(X_train.shape)

(120, 5)


In [79]:
#Iris_setosa_train

In [84]:
class linear_regression:
    def __init__(self,lr=0.01,epochs=1000):
        self.lr=lr
        self.epochs=epochs

    def fit(self,X,y):
        n_samples,n_features = X.shape
        self.weights=np.random.rand(n_features,1)

        for _ in range(self.epochs):
            y_pred=X@self.weights
            error=y_pred-y
            grad=(2/X.shape[0])*(X.T@error)
            self.weights-=self.lr*grad
      
    def predict(self,X):
        return X@self.weights

    
model_Iris_setosa=linear_regression(lr=0.01,epochs=100)
model_Iris_setosa.fit(X_train,Iris_setosa_train)

def to_class(pred):
        if pred<1: return 0
        else: return 1

y_predict_val= model_Iris_setosa.predict(X_val)
y_predict_val_class = np.array([to_class(p) for p in y_predict_val])

val_acc = np.mean(y_predict_val_class.reshape(-1,1) == Iris_setosa_val)
print("Validation Accuracy (80:20):", val_acc)

Validation Accuracy (80:20): 0.6666666666666666


In [86]:
X_train,Iris_versicolor_train,X_val,Iris_versicolor_val = train_val_split(X,Iris_versicolor,0.8,0.2)

model_Iris_versicolor=linear_regression(lr=0.01,epochs=100)
model_Iris_setosa.fit(X_train,Iris_versicolor_train)

y_predict_val= model_Iris_versicolor.predict(X_val)
y_predict_val_class = np.array([to_class(p) for p in y_predict_val])

val_acc = np.mean(y_predict_val_class.reshape(-1,1) == Iris_versicolor_val)
print("Validation Accuracy (80:20):", val_acc)

AttributeError: 'linear_regression' object has no attribute 'weights'

In [75]:
def mak_bal_dataset(name):
    y = np.array([1 if i==name else 0 for i in df['Species']]).reshape(-1,1)
    X = df.drop(columns=['Id','Species']).values
    X=(X-X.mean(axis=0))/X.std(axis=0)
    c=np.ones((X.shape[0],1))
    X=np.hstack([c,X])
    X_pos, y_pos = X[y.flatten()==1], y[y.flatten()==1]
    X_neg, y_neg = X[y.flatten()==0], y[y.flatten()==0]

    max_count = max(len(X_pos), len(X_neg))

    #balancing positives
    reps_pos = max_count // len(X_pos)
    rem_pos  = max_count % len(X_pos)
    X_pos_bal = np.vstack([X_pos]*reps_pos + [X_pos[:rem_pos]])
    y_pos_bal = np.vstack([y_pos]*reps_pos + [y_pos[:rem_pos]])

    #balancing negatives
    reps_neg = max_count // len(X_neg)
    rem_neg  = max_count % len(X_neg)
    X_neg_bal = np.vstack([X_neg]*reps_neg + [X_neg[:rem_neg]])
    y_neg_bal = np.vstack([y_neg]*reps_neg + [y_neg[:rem_neg]])

    #Combining bot + and -ves
    X_bal = np.vstack([X_pos_bal, X_neg_bal])
    y_bal = np.vstack([y_pos_bal, y_neg_bal])

    return X_bal, y_bal


In [62]:
X_setosa, y_setosa = mak_bal_dataset('Iris-setosa')
X_versicolor, y_versicolor = mak_bal_dataset('Iris-versicolor')
X_virginica, y_virginica = mak_bal_dataset('Iris-virginica')

In [64]:
#'Iris-setosa', 'Iris-versicolor', 'Iris-virginica'
X_setosa_train,y_setosa_train,X_setosa_val,y_setosa_val = train_val_split(X_setosa,y_setosa,0.8,0.2)
print(X_setosa_train.shape)

(160, 5)


In [78]:
model_setosa=linear_regression(lr=0.01,epochs=100)
model_setosa.fit(X_setosa_train,y_setosa_train)

y_predict_val= model_setosa.predict(X_setosa_val)
y_predict_val_class = np.array([to_class(p) for p in y_predict_val])

val_acc = np.mean(y_predict_val_class.reshape(-1,1) == y_setosa_val)
print("Validation Accuracy (80:20):", val_acc)

Validation Accuracy (80:20): 0.575


In [1]:
import numpy as np
import pandas as pd

def load_iris(path: str) -> pd.DataFrame:
    """Load the Iris CSV file."""
    df = pd.read_csv(path)
    return df

# ---------------------- 2. Utilities ---------------------- #
def make_dataset(df: pd.DataFrame, species_name: str) -> np.ndarray:
    """
    Create a binary target array: 1 for species_name, 0 for others.
    Shape -> (n_samples, 1)
    """
    return np.array([1 if s == species_name else 0 for s in df['Species']]
                   ).reshape(-1, 1)

def train_val_split(X: np.ndarray, y: np.ndarray,
                    train_size: float = 0.8,
                    seed: int = 113):
    """
    Stratified train/validation split.
    Returns: X_train, y_train, X_val, y_val
    """
    np.random.seed(seed)
    classes = np.unique(y)
    train_idx, val_idx = [], []
    for c in classes:
        idx = np.where(y == c)[0]
        np.random.shuffle(idx)
        n_train = int(len(idx) * train_size)
        train_idx.extend(idx[:n_train])
        val_idx.extend(idx[n_train:])
    np.random.shuffle(train_idx)
    np.random.shuffle(val_idx)
    return X[train_idx], y[train_idx], X[val_idx], y[val_idx]

def to_class(pred: float) -> int:
    """Convert regression output to class (0 or 1)."""
    return int(pred >= 1)   # threshold chosen to match original code

# ---------------------- 3. Simple Linear Regression ---------------------- #
class LinearRegression:
    def __init__(self, lr: float = 0.01, epochs: int = 1000):
        self.lr = lr
        self.epochs = epochs
        self.weights = None

    def fit(self, X: np.ndarray, y: np.ndarray):
        n_samples, n_features = X.shape
        self.weights = np.random.rand(n_features, 1)
        for _ in range(self.epochs):
            y_pred = X @ self.weights
            error = y_pred - y
            grad = (2 / n_samples) * (X.T @ error)
            self.weights -= self.lr * grad

    def predict(self, X: np.ndarray) -> np.ndarray:
        return X @ self.weights

# ---------------------- 4. Balanced Dataset ---------------------- #
def make_balanced_dataset(df: pd.DataFrame, species_name: str):
    """
    Make a balanced (1 vs rest) dataset for the given species.
    Adds a bias column and standardises features.
    Returns: X_bal, y_bal
    """
    y = make_dataset(df, species_name)
    X = df.drop(columns=['Id', 'Species']).values
    # Standardise features
    X = (X - X.mean(axis=0)) / X.std(axis=0)
    # Add bias term (column of ones)
    X = np.hstack([np.ones((X.shape[0], 1)), X])

    X_pos, y_pos = X[y.flatten() == 1], y[y.flatten() == 1]
    X_neg, y_neg = X[y.flatten() == 0], y[y.flatten() == 0]

    max_count = max(len(X_pos), len(X_neg))

    def oversample(X_cls, y_cls):
        reps = max_count // len(X_cls)
        rem = max_count % len(X_cls)
        return (np.vstack([X_cls] * reps + [X_cls[:rem]]),
                np.vstack([y_cls] * reps + [y_cls[:rem]]))

    X_pos_bal, y_pos_bal = oversample(X_pos, y_pos)
    X_neg_bal, y_neg_bal = oversample(X_neg, y_neg)

    X_bal = np.vstack([X_pos_bal, X_neg_bal])
    y_bal = np.vstack([y_pos_bal, y_neg_bal])
    return X_bal, y_bal

# ---------------------- 5. Training + Evaluation ---------------------- #
def run_one_vs_rest(df: pd.DataFrame, species_name: str):
    """Train & validate a simple regressor for one-vs-rest classification."""
    X_bal, y_bal = make_balanced_dataset(df, species_name)
    X_train, y_train, X_val, y_val = train_val_split(X_bal, y_bal, 0.8)

    model = LinearRegression(lr=0.01, epochs=100)
    model.fit(X_train, y_train)

    y_pred_val = model.predict(X_val)
    y_pred_class = np.array([to_class(p) for p in y_pred_val])
    val_acc = np.mean(y_pred_class.reshape(-1, 1) == y_val)

    print(f"{species_name:15s} Validation Accuracy: {val_acc:.3f}")

# ---------------------- 6. Main ---------------------- #
if __name__ == "__main__":
    path = r"D:\PycharmProjects\pythonProject\U23AI113\ML_lAB\LAB_5\archive (5)\Iris.csv"
    df = load_iris(path)

    for sp in ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']:
        run_one_vs_rest(df, sp)


Iris-setosa     Validation Accuracy: 0.625
Iris-versicolor Validation Accuracy: 0.500
Iris-virginica  Validation Accuracy: 0.600


C:\Users\RAJKUMAR BOKKISAM\AppData\Local\Temp\ipykernel_25004\2300779753.py:40: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(pred >= 1)   # threshold chosen to match original code
C:\Users\RAJKUMAR BOKKISAM\AppData\Local\Temp\ipykernel_25004\2300779753.py:40: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(pred >= 1)   # threshold chosen to match original code
C:\Users\RAJKUMAR BOKKISAM\AppData\Local\Temp\ipykernel_25004\2300779753.py:40: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing th

In [2]:
# --- After training the three binary models ---
species = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

# Train and keep all models
models = {}
for sp in species:
    X_bal, y_bal = make_balanced_dataset(df, sp)
    X_train, y_train, X_val, y_val = train_val_split(X_bal, y_bal, 0.8)
    model = LinearRegression(lr=0.01, epochs=100)
    model.fit(X_train, y_train)
    models[sp] = model

# -------- Predict the correct 3-class label -------- #
def predict_species(x_single: np.ndarray) -> str:
    """
    x_single : shape (n_features_without_bias,)
    Returns predicted species name.
    """
    # Standardise same way as training: mean/std from full df
    X_all = df.drop(columns=['Id', 'Species']).values
    mean, std = X_all.mean(axis=0), X_all.std(axis=0)
    x_std = (x_single - mean) / std
    x_with_bias = np.hstack([1, x_std]).reshape(1, -1)

    # get scores from each model
    scores = {sp: models[sp].predict(x_with_bias)[0, 0] for sp in species}

    # choose species with max score
    return max(scores, key=scores.get)

# Example: predict first row
sample = df.drop(columns=['Id', 'Species']).values[0]
print("True species :", df['Species'].iloc[0])
print("Predicted    :", predict_species(sample))


True species : Iris-setosa
Predicted    : Iris-setosa
