In [9]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"D:\PycharmProjects\pythonProject\U23AI113\ML_lAB\LAB_5\archive (5)\Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [4]:
df.shape

(150, 6)

In [11]:
species_map={"Iris-setosa":0, "Iris-versicolor":1, "Iris-virginica":2}
df['Species']=df['Species'].map(species_map)
#df['Species'].unique()
df['Species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [39]:
df['Species'].value_counts()

Species
0    50
1    50
2    50
Name: count, dtype: int64

In [13]:
X = df.drop(columns=['Id','Species']).values
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [14]:
mean=X.mean(axis=0)
mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

In [15]:
std=X.std(axis=0)
std

array([0.82530129, 0.43214658, 1.75852918, 0.76061262])

In [16]:
X=(X-mean)/std
X[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [20]:
c=np.ones((X.shape[0],1))
c.shape
X=np.hstack([c,X])
X.shape

(150, 5)

In [25]:
y=df['Species'].values.reshape(X.shape[0],1)
y.shape

(150, 1)

In [26]:
def train_val_test_split(X,y,train_size,val_size,test_size,seed=113):
    np.random.seed(seed)
    indices=np.arange(len(X))
    np.random.shuffle(indices)

    n_total=len(X)
    n_train=int(n_total*train_size)
    n_val=int(n_total*val_size)

    train=indices[:n_train]
    val=indices[n_train:n_train+n_val]
    test=indices[n_train+n_val:]
    return X[train],y[train],X[val],y[val],X[test],y[test]

X_train,y_train,X_val,y_val,X_test,y_test = train_val_test_split(X,y,0.8,0.1,0.1)
print(X_train.shape)
print(y_train.shape)
print(X_val.shape)
print(X_test.shape)
print(y_test.shape)

(120, 5)
(120, 1)
(15, 5)
(15, 5)
(15, 1)


In [32]:
class linear_regression:
    def __init__(self,lr=0.01,epochs=100):
        self.lr=lr
        self.epochs=epochs

    def fit(self,X,y):
        n_samples,n_features = X.shape
        self.weights=np.random.rand(n_features,1)

        for _ in range(self.epochs):
            y_pred=X@self.weights
            error=y_pred-y
            grad=(2/X.shape[0])*(X.T@error)
            self.weights-=self.lr*grad
      
    def predict(self,X):
        return X@self.weights

    
model=linear_regression(lr=0.01,epochs=100)
model.fit(X_train,y_train)

def to_class(pred):
        if pred<0.5: return 0
        elif pred<1.5: return 1
        else: return 2

y_predict_val= model.predict(X_val)
y_predict_val_class = np.array([to_class(p) for p in y_predict_val])

val_acc = np.mean(y_predict_val_class.reshape(-1,1) == y_val)
print("Validation Accuracy (80:10:10):", val_acc)

Validation Accuracy (80:10:10): 0.8


In [33]:
X_train,y_train,X_val,y_val,X_test,y_test = train_val_test_split(X,y,0.7,0.15,0.15)
model2=linear_regression(lr=0.01,epochs=100)
model2.fit(X_train,y_train)

y_predict_val= model2.predict(X_val)
y_predict_val_class = np.array([to_class(p) for p in y_predict_val])

val_acc = np.mean(y_predict_val_class.reshape(-1,1) == y_val)
print("Validation Accuracy (70:15:15):", val_acc)

Validation Accuracy (70:15:15): 0.9090909090909091


In [ ]:
#task 2
df=pd.read_csv(r"D:\PycharmProjects\pythonProject\U23AI113\ML_lAB\LAB_5\archive (5)\Iris.csv")
